### PR TITLE
feat(component): add accordion component and documentation

### PR DESCRIPTION
**Pull request by NeuroNexul**
### Description

The accordion component is a vertically stacked set of interactive headings that each contain a title, content, or both.

### What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [x] 📝 Documentation Update

### Mobile & Desktop Screenshots/Recordings

image

### CODE REVIEW

**Comment by ruru-m07** [comment]
### @NeuroNexul There is something that need updated.

image

This is preview looks good and it's perfect.

We need to change some default things. Can you make this setting default? Because the default Accordion style does not match the theme.

image

soo make default theme = "primary" and default Variant = "primary"


also we want here a button. that copy https://ruru-ui-git-fork-neuronexul-feat-componentaccordion-ruru-07.vercel.app/docs#faq

image

**Comment by ruru-m07** [comment]
### TODOS.

- [ ] update default styles
- [ ] update copy link button
- [ ] fix code snippets


looks like some imports are missing
image

**Comment by ruru-m07** [comment]
u can tack ref from here:- https://fumadocs.vercel.app/docs/ui/components/accordion

**Comment by NeuroNexul** [comment]
Okey... But for the copy button, I put it on user, if he wants he can add it, because copy button in accordion is not very common...

And the rest, I'll do it...

**Comment by ruru-m07** [comment]
> Okey... But for the copy button, I put it on user, if he wants he can add it, because copy button in accordion is not very common...
> 
> And the rest, I'll do it...

cool try to make it as a props. like enable Copy kind of...

**Comment by NeuroNexul** [comment]
And please grant me access to see the preview... I've requested...

**Comment by ruru-m07** [comment]
> And please grant me access to see the preview... I've requested...

okay.

**Comment by ruru-m07** [comment]
can we do a last thing to make docs more clean?

something like this highlight:- 

image

here I give some hints:-

image

image

image

⬆️ in above image for `trigger={` to `}` we can use multi line highlight like this.

image

also last one [Customizability](https://ruru-9g0bc1l23-ruru-07.vercel.app/docs/components/accordion#customizability) u can do some highlight to make code more readable.

**Review by ruru-m07 — APPROVED** [review]

**Comment by ruru-m07** [comment]
Thanks, @NeuroNexul for this beautiful component 🩷 , PR is now ready to merge. 🚀

**Pull request merged**
